<?xml version="1.0"?>

<robot name="rw" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Robot Parameters -->
    <xacro:property name="PI" value="3.14159265"/>
    <xacro:property name="body_length" value="0.96"/>
    <xacro:property name="body_width" value="1.04"/>
    <xacro:property name="body_height" value="0.819924"/>
    <xacro:property name="body_density" value="7850.0"/> <!-- Steel -->
    <xacro:property name="body_mass" value="${body_density * body_length * body_height * body_width}"/>
    <xacro:property name="body_inertia_x" value="${1.0/12.0 * body_mass * (body_height*body_height + body_width*body_width)}"/>
    <xacro:property name="body_inertia_y" value="${1.0/12.0 * body_mass * (body_length*body_length + body_height*body_height)}"/>
    <xacro:property name="body_inertia_z" value="${1.0/12.0 * body_mass * (body_length*body_length + body_width*body_width)}"/>

    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>

    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="wheel_separation" value="${body_width + wheel_width}"/>
    <xacro:property name="wheel_offset" value="${body_length/2 - wheel_radius}"/>
    <xacro:property name="wheel_density" value="900"/> <!-- Ruber -->
    <xacro:property name="wheel_mass" value="${wheel_density * PI * wheel_radius * wheel_radius * wheel_width}"/>
    <xacro:property name="wheel_inertia_x" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_y" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
    <xacro:property name="wheel_inertia_z" value="${1.0/2.0 * wheel_mass * wheel_radius * wheel_radius}"/>

    <xacro:property name="caster_wheel_offset_x" value="0.439948"/>
    <xacro:property name="caster_wheel_offset_y" value="0.490706"/>
    <xacro:property name="caster_wheel_offset_z" value="0.04"/>

    <xacro:property name="caster_wheel_radius" value="0.11"/>
    <xacro:property name="caster_offset" value="${body_length/2 - caster_wheel_radius}"/>
    <xacro:property name="caster_density" value="0.1"/>
    <xacro:property name="caster_mass" value="${caster_density * 4.0/3.0 * PI * caster_wheel_radius * caster_wheel_radius * caster_wheel_radius}"/>
    <xacro:property name="caster_inertia_x" value="${2.0/5.0 * caster_mass * caster_wheel_radius * caster_wheel_radius}"/>
    <xacro:property name="caster_inertia_y" value="${2.0/5.0 * caster_mass * caster_wheel_radius * caster_wheel_radius}"/>
    <xacro:property name="caster_inertia_z" value="${2.0/5.0 * caster_mass * caster_wheel_radius * caster_wheel_radius}"/>

    <xacro:property name="caster_wheel_offset_x" value="0.439948"/>
    <xacro:property name="caster_wheel_offset_y" value="0.490706"/>
    <xacro:property name="caster_wheel_offset_z" value="0.04"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="gray">
        <color rgba="0.7529 0.7529 0.7529 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>E
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Control Parameters -->
    <xacro:property name="max_linear_acceleration" value="20"/>

    <!-- Links -->

    <!-- Body Link -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/base_link.stl" />
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/base_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="50"/>
            <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <gazebo reference="base_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>        

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <link name="base_footprint"> 
    </link>

    <!-- Left Wheel -->
    <link name="left_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/left_wheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 -0.03 0.0" rpy="0.0 ${pi/2} ${pi/2}"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <inertial>
            <mass value="2"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </inertial>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${-body_width/2} 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="300.0"/>
        <dynamics damping="1" friction="1"/>
    </joint>

    <gazebo reference="left_wheel_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <!-- Right Wheel -->
    <link name="right_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/right_wheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.03 0.0" rpy="0.0 ${pi/2} ${pi/2}"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <inertial>
            <mass value="2"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.2"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </inertial>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 ${body_width/2} 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="300.0"/>
        <dynamics damping="1" friction="1"/>
    </joint>

    <gazebo reference="right_wheel_link">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
    </gazebo>

    <!-- FRONT RIGHT CASTER WHEEL LINK -->
    <link name="front_right_caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/front_right_Cwheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.0002"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="front_right_caster_wheel_joint" type="fixed">
        <origin xyz="${-caster_wheel_offset_x} ${-caster_wheel_offset_y} ${-caster_wheel_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_right_caster_wheel_link"/>
    </joint>

    <gazebo reference="front_right_caster_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <!-- FRONT LEFT CASTER WHEEL LINK -->
    <link name="front_left_caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/front_left_Cwheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.0002"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="front_left_caster_wheel_joint" type="fixed">
        <origin xyz="${-caster_wheel_offset_x} ${caster_wheel_offset_y} ${-caster_wheel_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_left_caster_wheel_link"/>
    </joint>

    <gazebo reference="front_left_caster_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <!-- BACK RIGHT CASTER WHEEL LINK -->
    <link name="back_right_caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/back_right_Cwheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.0002"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="back_right_caster_wheel_joint" type="fixed">
        <origin xyz="${caster_wheel_offset_x} ${-caster_wheel_offset_y} ${-caster_wheel_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_right_caster_wheel_link"/>
    </joint>

    <gazebo reference="back_right_caster_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <!-- BACK LEFT CASTER WHEEL LINK -->
    <link name="back_left_caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/back_left_Cwheel.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.0002"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="back_left_caster_wheel_joint" type="fixed">
        <origin xyz="${caster_wheel_offset_x} ${caster_wheel_offset_y} ${-caster_wheel_offset_z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_left_caster_wheel_link"/>
    </joint>

    <gazebo reference="back_left_caster_wheel_link">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <!-- IMU -->
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="imu_link" />
    </joint>

    <link name="imu_link">
    </link>

    <gazebo reference="imu_link">
        <sensor name="imu" type="imu">
        <always_on>1</always_on>
        <update_rate>50</update_rate>
        <visualize>true</visualize>
        <topic>imu</topic>
        <enable_metrics>true</enable_metrics>
        <gz_frame_id>imu_link</gz_frame_id>
        </sensor>
    </gazebo>

    <!-- GPS -->
    <joint name="navsat_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="navsat_link" />
    </joint>

    <link name="navsat_link">
    </link>

    <gazebo reference="navsat_link">
        <sensor name="navsat" type="navsat">
        <always_on>1</always_on>
        <update_rate>1</update_rate>
        <topic>navsat</topic>
        <gz_frame_id>navsat_link</gz_frame_id>
        </sensor>
    </gazebo>

    <!-- CAMERA 01 -->
    <link name="camera_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/front_camera.stl" />
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.483 0.000313 0.553294" rpy="0 ${-pi/2} 0"/>
    </joint>

    <link name="camera_link_optical"></link>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="0 ${pi/1.49} 0"/>
    </joint>

    <gazebo reference="camera_link_optical">
        <sensor name="rgbd_camera" type="rgbd_camera">
        <camera>
            <horizontal_fov>1.25</horizontal_fov>
            <image>
            <width>640</width>
            <height>480</height>
            </image>
            <clip>
            <near>0.3</near>
            <far>15</far>
            </clip>
            <optical_frame_id>camera_link_optical</optical_frame_id>
        </camera>
        <always_on>1</always_on>
        <update_rate>20</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
        <gz_frame_id>camera_link</gz_frame_id>
        </sensor>
    </gazebo>

    <!-- SIDE CAMERA -->
    <link name="camera2_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/front_camera.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <!-- Optional collision geometry to help avoid unintended physical interactions -->
        <collision>
            <geometry>
                <box size="0.025 0.025 0.025"/>
            </geometry>
        </collision>
    </link>

    <joint name="camera2_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera2_link"/>
        <!-- Offset the camera along the y-axis to avoid colliding with the front camera -->
        <origin xyz="-0.065 0.0 0.20" rpy="0 ${pi/4} 0"/>
    </joint>

    <link name="camera2_link_optical">
        <!-- This link can be used for defining the optical frame -->
    </link>

    <joint name="camera2_optical_joint" type="fixed">
        <parent link="camera2_link"/>
        <child link="camera2_link_optical"/>
        <origin xyz="-0.002 0 -0.11" rpy="0 ${pi/2} 0"/>
    </joint>

    <gazebo reference="camera2_link_optical">
        <sensor name="rgbd_camera2" type="rgbd_camera">
        <camera>
            <horizontal_fov>2</horizontal_fov>
            <image>
            <width>640</width>
            <height>640</height>
            </image>
            <clip>
            <near>0.001</near>
            <far>1</far>
            </clip>
            <optical_frame_id>camera2_link_optical</optical_frame_id>
        </camera>
        <always_on>1</always_on>
        <update_rate>20</update_rate>
        <visualize>true</visualize>
        <topic>camera2</topic>
        <gz_frame_id>camera2_link</gz_frame_id>
        </sensor>
    </gazebo>

    <!-- <gazebo reference="camera_link_optical">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image</topic>
        </sensor>
    </gazebo> -->

    <!-- LIDAR -->
    <link name="laser_frame">
        <visual>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/lidar.stl" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="file://$(find rw)/meshes/lidar.stl" />
            </geometry>
        </collision>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.48 -0.000058 0.40056" rpy="${-pi/2} 0 ${pi/2}"/>
    </joint>

    <link name="lidar_link_optical"></link>

    <joint name="lidar_optical_joint" type="fixed">
        <parent link="laser_frame"/>
        <child link="lidar_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} ${pi/2} 0"/>
    </joint>

    <gazebo reference="lidar_link_optical">

        <sensor name="gpu_lidar" type="gpu_lidar">
            <update_rate>30</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_link_optical</gz_frame_id>
            <lidar>
                <scan>
                <horizontal>
                    <samples>50</samples>
                    <!--(max_angle-min_angle)/samples * resolution -->
                    <resolution>1</resolution>
                    <min_angle>${-pi/4}</min_angle>
                    <max_angle>${pi/4}</max_angle>
                </horizontal>
                <!-- Dirty hack for fake lidar detections with ogre 1 rendering in VM -->
                <vertical>
                    <samples>50</samples>
                    <min_angle>${-pi/4}</min_angle>
                    <max_angle>${pi/8}</max_angle>
                </vertical>
                </scan>
                <range>
                <min>0.05</min>
                <max>70</max>
                <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
                <frame_id>lidar_link_optical</frame_id>
            </lidar>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <!-- Gazebo Plugins -->
    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <!-- Input -->
            <topic>cmd_vel</topic>
            <!-- <topic>cmd_vel_tracker</topic> -->

            <!-- Wheel joints -->
            <right_joint>left_wheel_joint</right_joint>
            <left_joint>right_wheel_joint</left_joint>
            <!-- Wheel parameters -->
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <!-- Control gains and limits -->
            <max_velocity>40.0</max_velocity>
            <max_linear_acceleration>10</max_linear_acceleration>
            <min_linear_acceleration>-10</min_linear_acceleration>
            <max_angular_acceleration>20</max_angular_acceleration>
            <min_angular_acceleration>-20</min_angular_acceleration>
            <max_linear_velocity>40</max_linear_velocity>
            <min_linear_velocity>-40</min_linear_velocity>
            <max_angular_velocity>10</max_angular_velocity>
            <min_angular_velocity>-10</min_angular_velocity>

            <!-- Output -->
            <odom_topic>odom</odom_topic>                  <!-- Odometry topic -->
            <tf_topic>tf</tf_topic>
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <odom_publish_frequency>30</odom_publish_frequency>
        </plugin>

        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>left_wheel_joint</joint_name>
            <joint_name>right_wheel_joint</joint_name>
        </plugin>

    </gazebo>

</robot>
